[theme]
  primaryColor             = "#e0303c"
  backgroundColor          = "#FFFFFF"
  secondaryBackgroundColor = "#f5f9fc"
  textColor                = "#313c45"
  font                     = "sans serif"
